- hosts: node2
  gather_facts: yes

  tasks:
   - name: create jenkins folder
     become: true
     file: 
      path: /usr/share/jenkins
      state: directory
      mode: 755
   - name: copy war to node host
     become: true
     copy: 
       src: /var/lib/jenkins/workspace/jenkins/war/target/jenkins.war
       dest: /usr/share/jenkins/jenkins.war
       mode: 755

   - name: run jenkins as service
     command: /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
