- hosts: node2
  gather_facts: yes

  tasks:
   - name: create jenkins folder
     become: true
     file: 
      path: /usr/share/jenkins
      state: directory
      mode: 755
   - name: copy war to node host
     become: true
     copy: 
       src: /var/lib/jenkins/workspace/jenkins/war/target/jenkins.war
       dest: /usr/share/jenkins/jenkins.war
       mode: 755