- hosts: node2
  gather_facts: yes

  tasks:
   - name: add repo for java
     become: true
     apt_repository:
       repo: ppa:webupd8team/java
   
   - name: Accept Java 8 License
     become: yes
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

   - name: install oracle java
     apt:
      name: oracle-java8-installer
      state: present

   - name: create jenkins folder
     become: true
     file: 
      path: /usr/share/jenkins
      state: directory
      mode: 755
   - name: create pid dir
     become: true
     file: 
      path: /var/run/jenkins/
      state: directory
      mode: 777

   - name: copy war to node host
     become: true
     copy: 
       src: /var/lib/jenkins/workspace/jenkins/war/target/jenkins.war
       dest: /usr/share/jenkins/jenkins.war
       mode: 755

   - name: run jenkins as service
     command: /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
