- hosts: node2
  gather_facts: yes
  become: true

  tasks:
   - name: add repo for java
     apt_repository:
       repo: ppa:webupd8team/java
   
   - name: Accept Java 8 License
     debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

   - name: install oracle java
     apt:
      name: oracle-java8-installer
      state: present

   - name: create jenkins folder
     file: 
      path: /usr/share/jenkins
      state: directory
      mode: 755
   - name: create pid dir
     file: 
      path: /var/run/jenkins/
      state: directory
      mode: 777

   - name: copy war to node host
     copy: 
       src: /var/lib/jenkins/workspace/jenkins/war/target/jenkins.war
       dest: /usr/share/jenkins/jenkins.war
       mode: 755

   - name: copy run script
     become: false
     copy: 
       src: files/jenkins.sh
       dest: ~/jenkins.sh
       mode: 755

#   - name: run jenkins 
#     command: /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
   - name: add jenkins service 
     template: src=jenkins.service.j2 dest=/etc/systemd/system/jenkins.service    

   - name: run jenkins
     systemd:
       state: started
       name: jenkins
